<?php
/*SELECIONA REGISTROS*/
	$GetRegQuimi = '
		SELECT
			amos_cada_iden,
			amos_cada_regi,
			amos_cada_orse,
			clie_cada_nome,
			fabr_cada_nome,
			mate_cada_descr,
			mate_cada_C,
  			mate_cada_Si,
  			mate_cada_Mn,
  			mate_cada_P,
  			mate_cada_S,
  			mate_cada_Cr,
  			mate_cada_Ni,
  			mate_cada_Mo,
  			mate_cada_Cu,
  			mate_cada_Al,
  			mate_cada_Fe,
  			mate_cada_V,
  			mate_cada_Co,
  			mate_cada_Nb,
  			mate_cada_Ti,
  			mate_cada_W,
  			mate_cada_Mg,
  			mate_cada_Zn,
  			mate_cada_Pb,
  			mate_cada_Sb,
  			mate_cada_Sn,
  			mate_cada_Ca,
  			mate_cada_Cl,
  			mate_cada_N,
  			mate_cada_Na,
  			mate_cada_Ceq,
			area_cada_descr,
			amos_cada_emis,
			amos_cada_descr,
			amos_cada_tenan,
			amos_cada_empre,
			IF( amos_cada_quimica = 1, "LABORATÓRIO", IF( amos_cada_campo_quimica = 1, "CAMPO", "" ) ) AS amos_cada_local,
			IFNULL( amos_quimi_cada_iden, "Automatico" ) AS amos_quimi_cada_iden,
			IFNULL( amos_quimi_cada_qtde, 1 ) AS amos_quimi_cada_qtde,
			IFNULL( amos_quimi_cada_result, -1 ) AS amos_quimi_cada_result,
			amos_quimi_cada_espe_C,
			amos_quimi_cada_obti_C,
			amos_quimi_cada_espe_Si,
			amos_quimi_cada_obti_Si,
  			amos_quimi_cada_espe_Mn,
  			amos_quimi_cada_obti_Mn,
  			amos_quimi_cada_espe_P,
  			amos_quimi_cada_obti_P,
  			amos_quimi_cada_espe_S,
  			amos_quimi_cada_obti_S,
  			amos_quimi_cada_espe_Cr,
  			amos_quimi_cada_obti_Cr,
  			amos_quimi_cada_espe_Ni,
  			amos_quimi_cada_obti_Ni,
  			amos_quimi_cada_espe_Mo,
  			amos_quimi_cada_obti_Mo,
  			amos_quimi_cada_espe_Cu,
  			amos_quimi_cada_obti_Cu,
  			amos_quimi_cada_espe_Al,
  			amos_quimi_cada_obti_Al,
  			amos_quimi_cada_espe_Fe,
  			amos_quimi_cada_obti_Fe,
  			amos_quimi_cada_espe_V,
  			amos_quimi_cada_obti_V,
  			amos_quimi_cada_espe_Co,
  			amos_quimi_cada_obti_Co,
  			amos_quimi_cada_espe_Nb,
  			amos_quimi_cada_obti_Nb,
  			amos_quimi_cada_espe_Ti,
  			amos_quimi_cada_obti_Ti,
  			amos_quimi_cada_espe_W,
  			amos_quimi_cada_obti_W,
  			amos_quimi_cada_espe_Mg,
  			amos_quimi_cada_obti_Mg,
  			amos_quimi_cada_espe_Zn,
  			amos_quimi_cada_obti_Zn,
  			amos_quimi_cada_espe_Pb,
  			amos_quimi_cada_obti_Pb,
  			amos_quimi_cada_espe_Sb,
  			amos_quimi_cada_obti_Sb,
  			amos_quimi_cada_espe_Sn,
  			amos_quimi_cada_obti_Sn,
  			amos_quimi_cada_espe_Ca,
  			amos_quimi_cada_obti_Ca,
  			amos_quimi_cada_espe_Cl,
  			amos_quimi_cada_obti_Cl,
  			amos_quimi_cada_espe_N,
  			amos_quimi_cada_obti_N,
  			amos_quimi_cada_espe_Na,
  			amos_quimi_cada_obti_Na,
  			amos_quimi_cada_espe_Ceq,
  			amos_quimi_cada_obti_Ceq,
			amos_quimi_cada_obs,
			IFNULL( amos_quimi_cada_fina, 0 ) AS amos_quimi_cada_fina,
			amos_quimi_cada_fina_data,
			amos_quimi_cada_fina_usua_iden,
			usua_cada_nome,
			sis_para_logo,
			sis_para_selo
		FROM
			labo_amos_cada
		LEFT JOIN
			labo_amos_quimi_cada
		ON
			( amos_quimi_cada_amos_iden = amos_cada_iden )
		LEFT JOIN
			labo_clie_cada
		ON
			( clie_cada_iden = amos_cada_clie_iden )
		LEFT JOIN
			labo_fabr_cada
		ON
			( fabr_cada_iden = amos_cada_fabr_iden )
		LEFT JOIN
			labo_mate_cada
		ON
			( mate_cada_iden = amos_cada_mate_iden )
		LEFT JOIN
			labo_area_cada
		ON
			( area_cada_iden = amos_cada_area_iden )
		LEFT JOIN
			sist_tenant_cada
		ON
			( tenant_cada_iden = amos_cada_tenan )
		LEFT JOIN
			sist_usua_cada
		ON
			( usua_cada_iden = amos_quimi_cada_fina_usua_iden )
		LEFT JOIN
			sist_para
		ON
			( sist_para_tenant = amos_cada_tenan AND
			  sist_para_empre = amos_cada_empre )
		WHERE
			( amos_cada_quimica = 1  OR
			  amos_cada_campo_quimica = 1 ) AND
			:FILTRO			
	';

/*INSERT REGISTROS*/
	$InstRegQuimi = '
		INSERT INTO labo_amos_quimi_cada (
			amos_quimi_cada_amos_iden,
			amos_quimi_cada_qtde,
			amos_quimi_cada_result,
			amos_quimi_cada_espe_C,
			amos_quimi_cada_obti_C,
			amos_quimi_cada_espe_Si,
			amos_quimi_cada_obti_Si,
  			amos_quimi_cada_espe_Mn,
  			amos_quimi_cada_obti_Mn,
  			amos_quimi_cada_espe_P,
  			amos_quimi_cada_obti_P,
  			amos_quimi_cada_espe_S,
  			amos_quimi_cada_obti_S,
  			amos_quimi_cada_espe_Cr,
  			amos_quimi_cada_obti_Cr,
  			amos_quimi_cada_espe_Ni,
  			amos_quimi_cada_obti_Ni,
  			amos_quimi_cada_espe_Mo,
  			amos_quimi_cada_obti_Mo,
  			amos_quimi_cada_espe_Cu,
  			amos_quimi_cada_obti_Cu,
  			amos_quimi_cada_espe_Al,
  			amos_quimi_cada_obti_Al,
  			amos_quimi_cada_espe_Fe,
  			amos_quimi_cada_obti_Fe,
  			amos_quimi_cada_espe_V,
  			amos_quimi_cada_obti_V,
  			amos_quimi_cada_espe_Co,
  			amos_quimi_cada_obti_Co,
  			amos_quimi_cada_espe_Nb,
  			amos_quimi_cada_obti_Nb,
  			amos_quimi_cada_espe_Ti,
  			amos_quimi_cada_obti_Ti,
  			amos_quimi_cada_espe_W,
  			amos_quimi_cada_obti_W,
  			amos_quimi_cada_espe_Mg,
  			amos_quimi_cada_obti_Mg,
  			amos_quimi_cada_espe_Zn,
  			amos_quimi_cada_obti_Zn,
  			amos_quimi_cada_espe_Pb,
  			amos_quimi_cada_obti_Pb,
  			amos_quimi_cada_espe_Sb,
  			amos_quimi_cada_obti_Sb,
  			amos_quimi_cada_espe_Sn,
  			amos_quimi_cada_obti_Sn,
  			amos_quimi_cada_espe_Ca,
  			amos_quimi_cada_obti_Ca,
  			amos_quimi_cada_espe_Cl,
  			amos_quimi_cada_obti_Cl,
  			amos_quimi_cada_espe_N,
  			amos_quimi_cada_obti_N,
  			amos_quimi_cada_espe_Na,
  			amos_quimi_cada_obti_Na,
  			amos_quimi_cada_espe_Ceq,
  			amos_quimi_cada_obti_Ceq,
			amos_quimi_cada_obs,
			amos_quimi_cada_fina,
			amos_quimi_cada_fina_data,
			amos_quimi_cada_fina_usua_iden
		) VALUES (
			:amos_quimi_cada_amos_iden,
			:amos_quimi_cada_qtde,
			:amos_quimi_cada_result,
			:amos_quimi_cada_espe_C,
			:amos_quimi_cada_obti_C,
			:amos_quimi_cada_espe_Si,
			:amos_quimi_cada_obti_Si,
  			:amos_quimi_cada_espe_Mn,
  			:amos_quimi_cada_obti_Mn,
  			:amos_quimi_cada_espe_P,
  			:amos_quimi_cada_obti_P,
  			:amos_quimi_cada_espe_S,
  			:amos_quimi_cada_obti_S,
  			:amos_quimi_cada_espe_Cr,
  			:amos_quimi_cada_obti_Cr,
  			:amos_quimi_cada_espe_Ni,
  			:amos_quimi_cada_obti_Ni,
  			:amos_quimi_cada_espe_Mo,
  			:amos_quimi_cada_obti_Mo,
  			:amos_quimi_cada_espe_Cu,
  			:amos_quimi_cada_obti_Cu,
  			:amos_quimi_cada_espe_Al,
  			:amos_quimi_cada_obti_Al,
  			:amos_quimi_cada_espe_Fe,
  			:amos_quimi_cada_obti_Fe,
  			:amos_quimi_cada_espe_V,
  			:amos_quimi_cada_obti_V,
  			:amos_quimi_cada_espe_Co,
  			:amos_quimi_cada_obti_Co,
  			:amos_quimi_cada_espe_Nb,
  			:amos_quimi_cada_obti_Nb,
  			:amos_quimi_cada_espe_Ti,
  			:amos_quimi_cada_obti_Ti,
  			:amos_quimi_cada_espe_W,
  			:amos_quimi_cada_obti_W,
  			:amos_quimi_cada_espe_Mg,
  			:amos_quimi_cada_obti_Mg,
  			:amos_quimi_cada_espe_Zn,
  			:amos_quimi_cada_obti_Zn,
  			:amos_quimi_cada_espe_Pb,
  			:amos_quimi_cada_obti_Pb,
  			:amos_quimi_cada_espe_Sb,
  			:amos_quimi_cada_obti_Sb,
  			:amos_quimi_cada_espe_Sn,
  			:amos_quimi_cada_obti_Sn,
  			:amos_quimi_cada_espe_Ca,
  			:amos_quimi_cada_obti_Ca,
  			:amos_quimi_cada_espe_Cl,
  			:amos_quimi_cada_obti_Cl,
  			:amos_quimi_cada_espe_N,
  			:amos_quimi_cada_obti_N,
  			:amos_quimi_cada_espe_Na,
  			:amos_quimi_cada_obti_Na,
  			:amos_quimi_cada_espe_Ceq,
  			:amos_quimi_cada_obti_Ceq,
			:amos_quimi_cada_obs,
			:amos_quimi_cada_fina,
			:amos_quimi_cada_fina_data,
			:amos_quimi_cada_fina_usua_iden
		);
	';

/*UPDATE REGISTROS*/
	$UpdtRegQuimi = '
		UPDATE labo_amos_quimi_cada SET 
			amos_quimi_cada_amos_iden = :amos_quimi_cada_amos_iden,
			amos_quimi_cada_qtde = :amos_quimi_cada_qtde,
			amos_quimi_cada_result = :amos_quimi_cada_result,
			amos_quimi_cada_espe_C = :amos_quimi_cada_espe_C,
			amos_quimi_cada_obti_C = :amos_quimi_cada_obti_C,
			amos_quimi_cada_espe_Si = :amos_quimi_cada_espe_Si,
			amos_quimi_cada_obti_Si = :amos_quimi_cada_obti_Si,
		  	amos_quimi_cada_espe_Mn = :amos_quimi_cada_espe_Mn,
		  	amos_quimi_cada_obti_Mn = :amos_quimi_cada_obti_Mn,
		  	amos_quimi_cada_espe_P = :amos_quimi_cada_espe_P,
		  	amos_quimi_cada_obti_P = :amos_quimi_cada_obti_P,
		  	amos_quimi_cada_espe_S = :amos_quimi_cada_espe_S,
		  	amos_quimi_cada_obti_S = :amos_quimi_cada_obti_S,
		  	amos_quimi_cada_espe_Cr = :amos_quimi_cada_espe_Cr,
		  	amos_quimi_cada_obti_Cr = :amos_quimi_cada_obti_Cr,
		  	amos_quimi_cada_espe_Ni = :amos_quimi_cada_espe_Ni,
		  	amos_quimi_cada_obti_Ni = :amos_quimi_cada_obti_Ni,
		  	amos_quimi_cada_espe_Mo = :amos_quimi_cada_espe_Mo,
		  	amos_quimi_cada_obti_Mo = :amos_quimi_cada_obti_Mo,
		  	amos_quimi_cada_espe_Cu = :amos_quimi_cada_espe_Cu,
		  	amos_quimi_cada_obti_Cu = :amos_quimi_cada_obti_Cu,
		  	amos_quimi_cada_espe_Al = :amos_quimi_cada_espe_Al,
		  	amos_quimi_cada_obti_Al = :amos_quimi_cada_obti_Al,
		  	amos_quimi_cada_espe_Fe = :amos_quimi_cada_espe_Fe,
		  	amos_quimi_cada_obti_Fe = :amos_quimi_cada_obti_Fe,
		  	amos_quimi_cada_espe_V = :amos_quimi_cada_espe_V,
		  	amos_quimi_cada_obti_V = :amos_quimi_cada_obti_V,
		  	amos_quimi_cada_espe_Co = :amos_quimi_cada_espe_Co,
		  	amos_quimi_cada_obti_Co = :amos_quimi_cada_obti_Co,
		  	amos_quimi_cada_espe_Nb = :amos_quimi_cada_espe_Nb,
		  	amos_quimi_cada_obti_Nb = :amos_quimi_cada_obti_Nb,
		  	amos_quimi_cada_espe_Ti = :amos_quimi_cada_espe_Ti,
		  	amos_quimi_cada_obti_Ti = :amos_quimi_cada_obti_Ti,
		  	amos_quimi_cada_espe_W = :amos_quimi_cada_espe_W,
		  	amos_quimi_cada_obti_W = :amos_quimi_cada_obti_W,
		  	amos_quimi_cada_espe_Mg = :amos_quimi_cada_espe_Mg,
		  	amos_quimi_cada_obti_Mg = :amos_quimi_cada_obti_Mg,
		  	amos_quimi_cada_espe_Zn = :amos_quimi_cada_espe_Zn,
		  	amos_quimi_cada_obti_Zn = :amos_quimi_cada_obti_Zn,
		  	amos_quimi_cada_espe_Pb = :amos_quimi_cada_espe_Pb,
		  	amos_quimi_cada_obti_Pb = :amos_quimi_cada_obti_Pb,
		  	amos_quimi_cada_espe_Sb = :amos_quimi_cada_espe_Sb,
		  	amos_quimi_cada_obti_Sb = :amos_quimi_cada_obti_Sb,
		  	amos_quimi_cada_espe_Sn = :amos_quimi_cada_espe_Sn,
		  	amos_quimi_cada_obti_Sn = :amos_quimi_cada_obti_Sn,
		  	amos_quimi_cada_espe_Ca = :amos_quimi_cada_espe_Ca,
		  	amos_quimi_cada_obti_Ca = :amos_quimi_cada_obti_Ca,
		  	amos_quimi_cada_espe_Cl = :amos_quimi_cada_espe_Cl,
		  	amos_quimi_cada_obti_Cl = :amos_quimi_cada_obti_Cl,
		  	amos_quimi_cada_espe_N = :amos_quimi_cada_espe_N,
		  	amos_quimi_cada_obti_N = :amos_quimi_cada_obti_N,
		  	amos_quimi_cada_espe_Na = :amos_quimi_cada_espe_Na,
		  	amos_quimi_cada_obti_Na = :amos_quimi_cada_obti_Na,
		  	amos_quimi_cada_espe_Ceq = :amos_quimi_cada_espe_Ceq,
		  	amos_quimi_cada_obti_Ceq = :amos_quimi_cada_obti_Ceq,
			amos_quimi_cada_obs = :amos_quimi_cada_obs,
			amos_quimi_cada_fina = :amos_quimi_cada_fina,
			amos_quimi_cada_fina_data = :amos_quimi_cada_fina_data,
			amos_quimi_cada_fina_usua_iden = :amos_quimi_cada_fina_usua_iden
		WHERE
			amos_quimi_cada_iden = :amos_quimi_cada_iden
	';
?>